### ISSUE TITLE
details example

### ISSUE THREAD

**Issue by jonan** [jonan/test#13]
<details>
 <summary>Stack Trace for `require('does.not.exist')`</summary>
 ```shell
 require('does.not.exist')
 Error: Cannot find module 'does.not.exist'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:286:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at repl:1:1
   at REPLServer.defaultEval (repl.js:164:27)
   at bound (domain.js:250:14)
   at REPLServer.runBound [as eval] (domain.js:263:12)
   at REPLServer.<anonymous> (repl.js:393:12)
   at emitOne (events.js:82:20)
 ```
</details>

**Comment by jonan** [comment]
Ttttt

**Comment by jonan** [comment]
https://github.com/square/okhttp/wiki

https://github.com/square/okhttp
